project:
  version: '1.0.0'

server:
  port: 8080

sprindocs:
  api-docs:
    path: /api-docs

spring:
  application:
    name: app
  config:
    activate:
      on-profile: lcl

---
spring:
  config:
    activate:
      on-profile: lcl
  data:
    mongodb:
      uri: mongodb+srv://${USER}:${PASSWORD}@cluster0.1owfgvr.mongodb.net/mongo?retryWrites=true&w=majority
